# Pi-Kinect Default Configuration
# This file contains default settings for the Pi-Kinect streaming system

# Network configuration
network:
  host: "0.0.0.0"  # Bind to all interfaces
  port: 8080       # HTTP server port
  timeout: 10      # Request timeout in seconds

# Camera configuration
camera:
  index: 0         # Camera device index
  width: 640       # Frame width
  height: 480      # Frame height
  fps: 30          # Target frame rate
  jpeg_quality: 85 # JPEG compression quality (1-100)

# Kinect-specific configuration
kinect:
  enabled: true           # Enable Kinect support
  auto_detect: true       # Automatically detect Kinect
  fallback_to_opencv: true # Fallback to OpenCV if Kinect fails
  depth_enabled: true     # Enable depth stream
  ir_enabled: false       # Enable IR stream (experimental)

# Logging configuration
logging:
  level: "INFO"           # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null              # Log file path (null for console only)
  max_size: 10485760      # Max log file size in bytes (10MB)
  backup_count: 5         # Number of backup log files

# Raspberry Pi connection settings
pi_ip: "192.168.1.9"     # Default Pi IP address
pi_username: "pi"         # SSH username
pi_password: null         # SSH password (use SSH keys for security)

# Development settings
debug: false              # Enable debug mode
profile: false            # Enable performance profiling
